### ISSUE TITLE
当容器没有包含 ls 指令时

### ISSUE THREAD

**Issue by fixnil** [ErikXu/kubernetes-filesystem#1]
是否可以使用 [临时容器](https://kubernetes.io/zh/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container) 的方式。

**Comment by ErikXu** [comment]
`kubectl debug` is an alpha feature of kubernetes v1.18 and being released in v1.20.
I have no kubernetes of v1.20 recently. 
I would try this after setting up a kubernetes of v1.20 .

**Comment by ErikXu** [comment]
We need to indicate the version of kubernetes firstly. 
If the version is above v.1.20 using `kubectl debug`, 
otherwise using `ls`command.

```bash
~ kubectl version --short
Client Version: v1.20.2
Server Version: v1.18.8
```

**Comment by ErikXu** [comment]
`kubectl debug` needs to enable ephemeral containers which is disable by default.

- Add `- --feature-gates=EphemeralContainers=true` to `/etc/kubernetes/manifests/kube-apiserver.yaml` in `master`.

Refer:

``` bash
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubeadm.kubernetes.io/kube-apiserver.advertise-address.endpoint: 10.0.0.38:6443
  creationTimestamp: null
  labels:
    component: kube-apiserver
    tier: control-plane
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-apiserver
    - --advertise-address=10.0.0.38
    - --allow-privileged=true
    ...
    - --feature-gates=EphemeralContainers=true # Enable ephemeral containers
``` 

Restart kubelet:

``` bash
systemctl daemon-reload
systemctl restart kubelet
```

- Add `- --feature-gates=EphemeralContainers=true` to `/usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf` in `all nodes`.

Refer:

``` bash
# Note: This dropin only works with kubeadm and kubelet v1.11+
[Service]
Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml --feature-gates=EphemeralContainers=true" # Enable ephemeral containers
...
```

Restart kubelet:

``` bash
systemctl daemon-reload
systemctl restart kubelet
```

**Comment by ErikXu** [comment]
The file directory seems to be different between `kubectl exec` and `kubectl debug`.

- kubectl exec

``` bash
[root@k8s-master ~]# kubectl exec -it nginx-7b7f4d878f-tt8jt -- sh -c "whereis nginx"
nginx: /usr/sbin/nginx /usr/lib/nginx /etc/nginx /usr/share/nginx
```

- kubectl debug
``` bash
[root@k8s-master ~]# kubectl debug -it nginx-7b7f4d878f-tt8jt --image=centos --target=nginx -- sh -c "whereis nginx"
Defaulting debug container name to debugger-nd4cz.
nginx:
```
